### ISSUE TITLE
More complex cases fail

### ISSUE THREAD

**Issue by 7studio** [dmarchena/postcss-color-rgb#1]
Hi David,

First of all, I want to apologise for the confusion about my [tweet](https://twitter.com/7studio/status/834025495201214464) announcing a duplicate postcss-color-rgb plugin :pensive:

I didn't find your plugin on [postcss.part](http://postcss.part) and I didn't know the official [plugin list](https://github.com/postcss/postcss/blob/master/docs/plugins.md)…
I should have looked if the npm package already existed but I am still not used to it.

Thanks to @ben-eb and @ai, I discovered your work.

However some of my tests don't pass with your plugin :disappointed_relieved:

It seems to me really difficult to handle these kinds of cases with RegExp:

```css
:root {
  --is-red: 0;
}

.foo {
  background-color: rgb( calc(255*var(--is-red) + 0*(1 - var(--is-red))) calc(0*var(--is-red) + 255*(1 - var(--is-red))) 0 / 1 );
}
```
this example comes from [Conditions for CSS Variables](http://kizu.ru/en/fun/conditions-for-css-variables/#conditions-for-colors).

or 

```css
.foo {
  color: rgb(255 0 51 / attr(data-alpha %, 100%));
}
```

The approach in my [plugin](https://github.com/7studio/postcss-color-rgb/) may help you enhance the official plugin.

Xavier.
